### ISSUE TITLE
Add StandardFirmataPlus

### ISSUE THREAD

**Issue by rwaldron** [johnny-five-io/nodebots-interchange#15]
https://github.com/firmata/arduino/tree/master/examples/StandardFirmataPlus

**Comment by ajfisher** [comment]
@rwaldron this is pretty easy to do now we have the firmata version specific stuff.

Question I have on this and maybe @soundanalogous can answer is what are the supported platforms for StandardFirmataPlus? That way I can build it appropriately.

**Comment by soundanalogous** [comment]
By supported platforms do you mean Arduino boards (and clones) or do you mean Arduino vs Particle vs ChipKit, etc?

**Comment by ajfisher** [comment]
Arduino boards. My understanding (from only a cursory look) is that
Standard Firmata Plus requires some additional memory etc so probably won't
run on all arduinos?

**Comment by soundanalogous** [comment]
It currently runs on all boards supported by Arduino 1.6.6 except Gemma (ATtiny-based). Also runs on all of the Teensy boards. Once one more big feature (such as SPI) is added, it will likely no longer run reliably on ATmega328p and ATmega32u4 boards.

**Comment by ajfisher** [comment]
Okay, given that, I think we don't support those boards out of the gate
rather than remove it later on and cause confusion. If it ends up being
supportable then that's cool and we can add it later.

**Comment by soundanalogous** [comment]
Unfortunately those are the most popular boards. I really wish people would stop creating new boards with the ATmega32u4. It just doesn't have enough Flash and RAM.

**Comment by ajfisher** [comment]
Yeah. Feels like a lot of clone design is because "everyone else does it
like that" rather than "let's improve the design"
