### ISSUE TITLE
Setting backpack into config mode

### ISSUE THREAD

**Issue by anno143** [johnny-five-io/nodebots-interchange#17]
Hi!
I am trying to install hc-sr04 on my arduino uno. i am getting the following error
`Can't configure device. Did you remember to set your backpack into config mode`
so How can i set my "backpack into config mode`?
(Don't mind i am new to node development)

**Comment by frxnz** [comment]
I was just noticing this is missing from the docs this morning.

Configuring the backpack firmware requires you to pull pin 2 high. Basically you connect pin 2 to a 5V pin with a jumper, and then flash the board.
