### ISSUE TITLE
Receiving Error: Sending 3020: receiveData timeout after 400ms

### ISSUE THREAD

**Issue by neurotech** [johnny-five-io/nodebots-interchange#22]
Hi there. I am trying to use `interchange` to install `node-pixel` as described here: https://github.com/ajfisher/node-pixel/blob/master/docs/installation.md#i2c-backpack

I'm not sure if this is something to be worried about, but this is what is returned by the command:
```
$ interchange install git+https://github.com/ajfisher/node-pixel -a nano
Retrieving manifest data from GitHub
Downloading hex file
found nano on port /dev/cu.usbserial-A702U0S6
connected
reset complete.
flashing, please wait...
flash complete.
Error: Sending 3020: receiveData timeout after 400ms
    at /usr/local/lib/node_modules/nodebots-interchange/node_modules/stk500/lib/sendCommand.js:36:17
    at finished (/usr/local/lib/node_modules/nodebots-interchange/node_modules/stk500/lib/receiveData.js:38:5)
    at Timeout._onTimeout (/usr/local/lib/node_modules/nodebots-interchange/node_modules/stk500/lib/receiveData.js:43:7)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
```

**Comment by ajfisher** [comment]
You're probably not using a nano - use `-a uno` instead or whatever is the
board type you're using.

**Comment by neurotech** [comment]
I am using a SparkFun RedBoard.

**Comment by keaixx365** [comment]
@neurotech  how can you get this issue resolved?

**Comment by thebirdgr** [comment]
In 2020, I have this problem too. Anyone know the fix?

**Comment by neurotech** [comment]
It's been a while, but I'm pretty sure I never resolved this issue on my end.

**Comment by thebirdgr** [comment]
Thanks for the reply on this post! 
Oh that's unfortunate, same here, I decided to just code my Arduino in C++ rather than use Johnny-five.
