### ISSUE TITLE
Can't get nodebots-interchange installed

### ISSUE THREAD

**Issue by dubaleeiro** [johnny-five-io/nodebots-interchange#34]
Hi,
There is no way I can get nodebots-interchange intalled on a raspberry pi zero w, even having formatted the SD card twice. I am triggering the command ` npm install nodebots-interchange` from folder `~/.node-red` like any other npm package. The package seem to be installed but when I try to run the command `interchange` following error msg appear:
`bash: interchange: comand not found`

This is the message I get after running `npm install nodebots-interchange`:
`npm WARN node-red-project@0.0.1 No repository field.
npm WARN node-red-project@0.0.1 No license field.

+ nodebots-interchange@1.3.0
updated 1 package and moved 3 packages in 139.879s`

Additional info:
`npm --version` is 5.6.0
`node --version` is v8.11.4
OS: "Raspbian GNU/Linux 9 (stretch)"

Thanks!

**Comment by ajfisher** [comment]
So there's probably a couple of reasons this may not work.

1. Install interchange using the -g switch to install it globally

`npm install -g nodebots-interchange`

2 add "./.bin" to your PATH variable in your .profile or .bashrc file

If it didn't fail when you installed, which looking at your report it
didn't then one of the above should work.

**Comment by ajfisher** [comment]
Mostly you're using interchange to just install your backpack. If you've got that working then that will be fine.

There's not a node-red plug in for node-pixel but you can just create a function node / script node and then push code to it over a johnny-five connection.

**Comment by dubaleeiro** [comment]
I will try. Thank you very much!

**Comment by swiftmypants** [comment]
How were you able to finally get it installed? Mine seems to fail at serial port install every time.

**Comment by ajfisher** [comment]
@swiftmypants is this failing under the same conditions? On a raspberry pi? If so can you post what is happening for me and I'll reopen this ticket? If not, can you open a new issue?
